### ISSUE TITLE
PanelController should have a listener for when the panel slides

### ISSUE THREAD

**Issue by akshathjain** [akshathjain/sliding_up_panel#10]
The PanelController should have a listener that subscribes to the animation controller and is called every time the animation changes (i.e. the panel slides open/closed). This can be useful for adding custom animations that are based on the panel position. For example:
```dart
PanelController pc = new PanelController();

pc.addOnPanelSlideListener((double position){
  print(position); //0.0 to 1.0 where 0.0 is full collapsed and 1.0 is fully open
});
```

**Comment by aytunch** [comment]
First of all thanks for this cool Library. I hope it gets better. It looks good.

About this issue: Not only the position but we also definitely need delegate functions like onPanelOpen, onPanelClose, onPanelShow, onPanelHide.

And we need properties like _panelController.isHidden, isShown, isCollapsable etc along with the position property. It is not cool to check if (position==_panelController.maxHeight) to understand that it is isShown.

**Comment by akshathjain** [comment]
@aytunch Not sure about the necessity for onPanelShow, onPanelHide since show and hide are called directly by the user, but I can definitely see onPanelOpened and onPanelClosed being useful. As well as panelController.isHidden, isShown, etc.
