### ISSUE TITLE
SlidePanel Over BottomTabbar

### ISSUE THREAD

**Issue by eopeter** [akshathjain/sliding_up_panel#101]
How will I put this over a bottomNavigationBar? Still want to have access to the tabs while panel is collapsed

**Comment by akshathjain** [comment]
You can place the `SlidingUpPanel` inside of a stack, and then use a `Positioned` widget to adjust its bottom offset to be above the `bottomNavigationBar`

**Comment by ghenry** [comment]
I'm just putting BottomNavigationBar as a child of the SlidingUpPanel. Works well.

**Comment by mroignant** [comment]
Hello, 

Hope everyone is fine.

I would like to hide the BottomNavigationBar when the component SlidingUpPanel is going down.

I used the property "onPanelSlide" with the position of the SlideUpPanel component but there are lags...
It's not convenient.

I would like to have the same behavior of Airbnb application. (Version 2023)

Do you have any ideas..?

Thank you in advance of your help.

Mika
