### ISSUE TITLE
Buttons on top

### ISSUE THREAD

**Issue by dimityrivanov** [akshathjain/sliding_up_panel#104]
Is it possible to attach buttons on top of that view that moves with the panel when collapsed or not ?

**Comment by aboutmydreams** [comment]
some problem ,
#### the red bottom cant onpress
![image](https://user-images.githubusercontent.com/34613360/75599267-264c5e00-5ade-11ea-8a4a-5f0c7735ded6.png)

**Comment by akshathjain** [comment]
@dimityrivanov Yes, check out the FAB in the example project and look at #109 for a recommendation for a more efficient implementation.

@aboutmydreams Please reopen in a new issue with more information (using the 'Bug report' template).
