### ISSUE TITLE
Controlling the animation curve / duration of sliding animation

### ISSUE THREAD

**Issue by illuminated** [akshathjain/sliding_up_panel#107]
I want to slide up the panel after all the widgets have been rendered on screen (kind of an _on load preview_ of the contents of the body) and then slide up the panel.

I can do that with animatePanelToPosition within the initState, but what bothers me is there is no animation in this process... The panel just pops up in few milliseconds. Is there a way to change this? Ideally, to be able to set both the animation curve and the duration of animation?

**Comment by wedza** [comment]
Seems like [it is already a planned feature](https://github.com/akshathjain/sliding_up_panel/blob/036238e74fcc5ab2581b886617ff2beb077b7504/lib/src/panel.dart#L422).

In the waiting of this, [I tweaked this line in my project](https://github.com/akshathjain/sliding_up_panel/blob/036238e74fcc5ab2581b886617ff2beb077b7504/lib/src/panel.dart#L425).

**Comment by giga10** [comment]
I need this too. 😀

**Comment by akshathjain** [comment]
@illuminated using the `animatePanelToPosition` method should have an animation on the panel by default. Can you provide a sample `main.dart` that causes the sudden jump? 

I'll also add the animation curve / duration to the panel controller in v1.0.1.

**Comment by akshathjain** [comment]
I'm going to go ahead and close this issue for now since I've added the requested functionality. If you're still not able to animate the panel after v1.0.1 is released, feel free to reopen this.
