### ISSUE TITLE
Close panel on backdrop drag

### ISSUE THREAD

**Issue by craggy2593** [akshathjain/sliding_up_panel#108]
Is there any way of closing the panel on dragging the backdrop in the direction of the panel close? 

There is the ability to close on tap with `backdropTapClosesPanel`, and dragging within the panel when using a `panelBuilder` will close accordingly, but when dragging within the backdrop area, any interactions are ignored.

**Comment by akshathjain** [comment]
You can create a custom `GestureDetector` over your body and check for drags that way. On a drag, you can use the `PanelController` and call `_pc.close()`.

**Comment by akshathjain** [comment]
Related to #24, #70, #121. This has been implemented and will be pushed in v1.0.1.
