### ISSUE TITLE
Tap on panel body as first gesture closes the panel.

### ISSUE THREAD

**Issue by Bad-Mother-Fucker** [akshathjain/sliding_up_panel#111]
I'm using panelBuilder and a SingleChildScrollView as panel body. If I scroll first and then tap nothing happens and works fine. If I first tap on the body the panel closes immediately.

**Comment by shlima** [comment]
Have the same issue

**Comment by shlima** [comment]
The same issue but with the different behaviour. The panel closes by itself when:

1) I open it programmatically (controller.open)
1) I click on an element (button) inside the panel
1) if I use a scroll inside the panel before clicking on the button inside it, the panel does not close spontaneously

`SlidingUpPanel` has been initialized with `panelBuilder` in my case.

**Comment by Bad-Mother-Fucker** [comment]
> The same issue but with the different behaviour. The panel closes by itself when:
> 
> 1. I open it programmatically (controller.open)
> 2. I click on an element (button) inside the panel
> 3. if I use a scroll inside the panel before clicking on the button inside it, the panel does not close spontaneously
> 
> `SlidingUpPanel` has been initialized with `panelBuilder` in my case.

I found a workaround using a global key to access the state and call open() method. In this way it will not close automatically

**Comment by akshathjain** [comment]
I believe this to be related to issue #102, which has been resolved. Closing this issue for now, but feel free to reopen it if v1.0.1 of the package doesn't fix it.

**Comment by shlima** [comment]
Can confirm the issue has been resolved, thank you.
