### ISSUE TITLE
Animate panel from collapsed to hidden (and vice versa)? (Reopen issue #100)

### ISSUE THREAD

**Issue by giga10** [akshathjain/sliding_up_panel#123]
Hey @akshathjain 

Just to let you know that #100 is NOT fixed in v1.0.1 with adding SnapPoint feature, simply because it has nothing to do with it in the first place. I probably phrased it badly in the original issue description. Sorry for that.

My "request" there was actually - adding animation for show() / hide() methods.

It is (I guess) related to #56.

**Comment by akshathjain** [comment]
I'm closing this and reopening the original thread.
