### ISSUE TITLE
Changing panelBody at runtime

### ISSUE THREAD

**Issue by ArefMozafari** [akshathjain/sliding_up_panel#125]
Hi there
how can i change the panelBody at the run time? because i'm using the panel for in my root widget and for each item that user selected in current screen i need to show different body for in the panel

**Comment by akshathjain** [comment]
I'd recommend maintaining an enum that describes all the states of your panel. When the state is supposed to change, call `setState()` and update an enum variable. For example:

```dart
enum PanelWidgetState{
    WIDGET_ONE,
    WIDGET_TWO
}

PanelWidgetState _pws;

Widget build(BuildContext context){
    return SlidingUpPanel(
        panel: _panel(),
        ...
    );
}

Widget _panel(){
    if ( _pws == PanelWidgetState.WIDGET_ONE) return WidgetOne();
    else if ...
}
```

**Comment by ArefMozafari** [comment]
Thank you
