### ISSUE TITLE
panel does not dismiss when backdropEnabled: true

### ISSUE THREAD

**Issue by aytunch** [akshathjain/sliding_up_panel#13]
When the user presses anywhere except the panel, the panel should hide. But right now nothing happens. 

Also, the backdrop overlay only covers the body of the Scaffold. BottomNavigationBar and AppBar are not greyed out.

**Comment by akshathjain** [comment]
@aytunch Can you split this into 2 issues? That is, can you create a new issue for the the second part: "the backdrop overlay only covers the body of the Scaffold. BottomNavigationBar and AppBar are not greyed out"?

**Comment by aytunch** [comment]
Ok The new issue is created

**Comment by akshathjain** [comment]
I'll add this as a feature in the next release under the property `backdropTapDismissesPanel` or something like that. It'll be set to `true` by default and can be changed to allow for the maximum amount of flexibility.

**Comment by aytunch** [comment]
@akshathjain sounds great
