### ISSUE TITLE
minSnapDistance for hide

### ISSUE THREAD

**Issue by aytunch** [akshathjain/sliding_up_panel#16]
Right now the y position user needs to bring the panel down for it to disappear is fixed(or maybe a fraction of the maxHeight). Developer should be able to set this according to his/her own needs imho.

**Comment by akshathjain** [comment]
@aytunch You're right, this should definitely be customizable. Currently, the minimum distance to trigger a snap open/closed is 50% of the (maxHeight - minHeight).

**Comment by akshathjain** [comment]
Closing for now since this behavior isn't clearly defined when using a `snapPoint`.
