### ISSUE TITLE
Is there any way I can keep the panel open until I get to the top of the listview

### ISSUE THREAD

**Issue by andrej188** [akshathjain/sliding_up_panel#167]
Right so this is where I am stuck. I have a listview with items in the sliding panel, and when I scroll the listview the panel also moves down, is there anyway I can keep the panel open until I get to the end of the listview?

**Comment by JulianBissekkou** [comment]
Did you set the `ScrollController` correctly? 

```dart
SlidingUpPanel(
  panelBuilder: (controller) => ListView(controller: controller,...),
)
```

**Comment by andrej188** [comment]
> Did you set the `ScrollController` correctly?
> 
> ```dart
> SlidingUpPanel(
>   panelBuilder: (controller) => ListView(controller: controller,...),
> )
> ```

This fixed it, thank you so much! @JulianBissekkou
