### ISSUE TITLE
Infinite height?

### ISSUE THREAD

**Issue by siddzankat** [akshathjain/sliding_up_panel#17]
First of all, it's great implementation. I have been looking for a widget like this for a while and I had implemented it from scratch but it was no where as smooth as your implementation. I have been playing around with different properties but i am not able to implement it with infinite height or with height that's larger than screen size. I am trying implement it with floating effect, so how would i implement when height is larger than screen size? i want it to scroll/drag as long as there are items. Thanks in advance!

**Comment by akshathjain** [comment]
Thanks! 

Are you trying to implement the `SlidingUpPanel` with a ListView (or something similar) nested inside? I'm not sure I completely understand how you're trying to implement this. For example, if you have a large list inside of the `panel`, you could set `maxHeight` to be `MediaQuery.of(context).size.height` so that way when open, the panel takes up the entire screen (and gives the effect that the panel is still moving but its actually the list nested inside).

**Comment by MaskyS** [comment]
@akshathjain Awesome package! I was searching for something similar earlier, tried https://github.com/ricnaaru/scrollable_bottom_sheet but eventually switched to another UI flow. 

Consider helping others find this project by adding the bottom sheet keyword somewhere since that's what Google calls it. https://material.io/design/components/sheets-bottom.html#usage

**Comment by akshathjain** [comment]
@MaskyS Good idea! I'll update the docs to include "bottom sheet" or make a reference to Google's terminology.

**Comment by siddzankat** [comment]
> Thanks!
>

**Comment by siddzankat** [comment]
I am trying to implement something like this: https://gfycat.com/pastelgenerousgoosefish.
Another example is Google Maps Android App. I think you understand it correctly. I want to be able to drag content from bottom to top and keep scrolling if I have more and more content. 
I tried implementing Listview nested inside the way you suggested but seems like when gesture detecter detects my touch, it would start scrolling the list inside and doesn't drag the sliding panel first to open it. Thanks in Advance!

**Comment by akshathjain** [comment]
@siddzankat Ok, I think I might have an idea on how to implement this using custom ScrollBehaviors. I'll look into more over the next few days and comment again if I find a better solution. I also update the docs with it so anyone who's looking for the same feature in the future can easily find it.

**Comment by siddzankat** [comment]
Awesome. Thanks in advance, Akshath!

**Comment by akshathjain** [comment]
@siddzankat I think I found a solution! Here's what my `main.dart` looks like. Full disclosure: there's currently a bug that if you swipe up on the panel, then immediately swipe down, the panel doesn't close. Instead, you need to scroll a little, and then swipe down again (when you're at the top of the Scrollable portion) to close the panel. I'm currently working on a fix, but here's something to start with. (there are also probably other edge case bugs as well).

```dart
import 'package:flutter/material.dart';
import 'package:sliding_up_panel/sliding_up_panel.dart';

void main() => runApp(Playground());

class Playground extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      title: 'Playground',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: HomePage(),
    );
  }
}

class HomePage extends StatefulWidget {
  @override
  _HomePageState createState() => _HomePageState();
}


class _HomePageState extends State<HomePage> {

  ScrollController _sc = new ScrollController();
  PanelController _pc = new PanelController();
  bool disableScroll = true;

  @override
  void initState() {
    super.initState();
    _sc.addListener((){
      setState((){
        if(_pc.isPanelOpen()){
          disableScroll = _sc.offset <= 0;
        }
      });
    });
  }

  @override
  Widget build(BuildContext context){
    return Material(
      child: SlidingUpPanel(
        panel: _panel(),
        controller: _pc,
        maxHeight: MediaQuery.of(context).size.height,
        minHeight: 200.0,
        backdropEnabled: true,
        onPanelOpened: (){
          setState(() {
            disableScroll = false;
          });
        },
        onPanelClosed: (){
          setState(() {
            disableScroll = true;
          });
        },
      ),
    );
  }

  Widget _panel(){
    return ListView.builder(
      itemCount: 50,
      controller: _sc,
      physics: disableScroll ? NeverScrollableScrollPhysics() : ClampingScrollPhysics(),
      itemBuilder: (BuildContext context, int i){
        return Container(
          padding: const EdgeInsets.all(12.0),
          child: Text("$i"),
        );
      },
    );
  }

}
```

Essentially, what I'm doing is controlling whether or not the `ListView` is able to scroll based on the position of the panel. Disabling the ability to scroll essentially passes gestures underneath the `ListView` and to the panel, which allows the panel to open/close.

Since this is a rather important use case for the `SlidingUpPanel`, I'm going to work on integrating this functionality more seamlessly into the API in future releases.

**Comment by siddzankat** [comment]
This is awesome. Thanks @akshathjain

**Comment by vmihalachi** [comment]
Hi @akshathjain any news on this? :)

**Comment by RicardoRB** [comment]
Hi @akshathjain I can try to implemented it but why this is a bug?

**Comment by mausamRayamajhi** [comment]
I think, I have solve this scroll issue with listView inside panel. Code is attached
![1](https://user-images.githubusercontent.com/28975010/60766881-7e59ce80-a0cf-11e9-8096-9274fd0b6af4.png)
![2](https://user-images.githubusercontent.com/28975010/60766885-87e33680-a0cf-11e9-8cbb-86a5e2148058.png)
![3](https://user-images.githubusercontent.com/28975010/60766888-8c0f5400-a0cf-11e9-95a2-80abf5882dda.png)

**Comment by rydrdev** [comment]
> @akshathjain your code snippet from here: https://github.com/akshathjain/sliding_up_panel/issues/17#issuecomment-482770287 works pretty well, though it seems to throw an error if you play around with dragging / scrolling and then dragging again. See error below:


```
The following assertion was thrown while handling a gesture:
'package:flutter/src/widgets/scrollable.dart': Failed assertion: line 480 pos 12: '_drag == null': is not true.


Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=BUG.md

When the exception was thrown, this was the stack
#2      ScrollableState._handleDragDown 
package:flutter/…/widgets/scrollable.dart:480
#3      DragGestureRecognizer._checkDown.<anonymous closure> 
package:flutter/…/gestures/monodrag.dart:359
#4      GestureRecognizer.invokeCallback 
package:flutter/…/gestures/recognizer.dart:182
#5      DragGestureRecognizer._checkDown 
package:flutter/…/gestures/monodrag.dart:359
#6      DragGestureRecognizer.addAllowedPointer 
package:flutter/…/gestures/monodrag.dart:236
...
Handler: "onDown"
Recognizer: VerticalDragGestureRecognizer#e028f
    start behavior: start
```

Is there a fix for this from what you know? Thanks

**Comment by semsturgut** [comment]
> > @akshathjain your code snippet from here: [#17 (comment)](https://github.com/akshathjain/sliding_up_panel/issues/17#issuecomment-482770287) works pretty well, though it seems to throw an error if you play around with dragging / scrolling and then dragging again. See error below:
> 
> ```
> The following assertion was thrown while handling a gesture:
> 'package:flutter/src/widgets/scrollable.dart': Failed assertion: line 480 pos 12: '_drag == null': is not true.
> 
> 
> Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
> In either case, please report this assertion by filing a bug on GitHub:
>   https://github.com/flutter/flutter/issues/new?template=BUG.md
> 
> When the exception was thrown, this was the stack
> #2      ScrollableState._handleDragDown 
> package:flutter/…/widgets/scrollable.dart:480
> #3      DragGestureRecognizer._checkDown.<anonymous closure> 
> package:flutter/…/gestures/monodrag.dart:359
> #4      GestureRecognizer.invokeCallback 
> package:flutter/…/gestures/recognizer.dart:182
> #5      DragGestureRecognizer._checkDown 
> package:flutter/…/gestures/monodrag.dart:359
> #6      DragGestureRecognizer.addAllowedPointer 
> package:flutter/…/gestures/monodrag.dart:236
> ...
> Handler: "onDown"
> Recognizer: VerticalDragGestureRecognizer#e028f
>     start behavior: start
> ```
> 
> Is there a fix for this from what you know? Thanks

I have the same problem, did you fix it?

**Comment by fremfi** [comment]
> > > @akshathjain your code snippet from here: [#17 (comment)](https://github.com/akshathjain/sliding_up_panel/issues/17#issuecomment-482770287) works pretty well, though it seems to throw an error if you play around with dragging / scrolling and then dragging again. See error below:
> > 
> > 
> > ```
> > The following assertion was thrown while handling a gesture:
> > 'package:flutter/src/widgets/scrollable.dart': Failed assertion: line 480 pos 12: '_drag == null': is not true.
> > 
> > 
> > Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
> > In either case, please report this assertion by filing a bug on GitHub:
> >   https://github.com/flutter/flutter/issues/new?template=BUG.md
> > 
> > When the exception was thrown, this was the stack
> > #2      ScrollableState._handleDragDown 
> > package:flutter/…/widgets/scrollable.dart:480
> > #3      DragGestureRecognizer._checkDown.<anonymous closure> 
> > package:flutter/…/gestures/monodrag.dart:359
> > #4      GestureRecognizer.invokeCallback 
> > package:flutter/…/gestures/recognizer.dart:182
> > #5      DragGestureRecognizer._checkDown 
> > package:flutter/…/gestures/monodrag.dart:359
> > #6      DragGestureRecognizer.addAllowedPointer 
> > package:flutter/…/gestures/monodrag.dart:236
> > ...
> > Handler: "onDown"
> > Recognizer: VerticalDragGestureRecognizer#e028f
> >     start behavior: start
> > ```
> > 
> > 
> > Is there a fix for this from what you know? Thanks
> 
> I have the same problem, did you fix it?

same here. anyone found a fix?

**Comment by semsturgut** [comment]
> > > > @akshathjain your code snippet from here: [#17 (comment)](https://github.com/akshathjain/sliding_up_panel/issues/17#issuecomment-482770287) works pretty well, though it seems to throw an error if you play around with dragging / scrolling and then dragging again. See error below:
> > > 
> > > 
> > > ```
> > > The following assertion was thrown while handling a gesture:
> > > 'package:flutter/src/widgets/scrollable.dart': Failed assertion: line 480 pos 12: '_drag == null': is not true.
> > > 
> > > 
> > > Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
> > > In either case, please report this assertion by filing a bug on GitHub:
> > >   https://github.com/flutter/flutter/issues/new?template=BUG.md
> > > 
> > > When the exception was thrown, this was the stack
> > > #2      ScrollableState._handleDragDown 
> > > package:flutter/…/widgets/scrollable.dart:480
> > > #3      DragGestureRecognizer._checkDown.<anonymous closure> 
> > > package:flutter/…/gestures/monodrag.dart:359
> > > #4      GestureRecognizer.invokeCallback 
> > > package:flutter/…/gestures/recognizer.dart:182
> > > #5      DragGestureRecognizer._checkDown 
> > > package:flutter/…/gestures/monodrag.dart:359
> > > #6      DragGestureRecognizer.addAllowedPointer 
> > > package:flutter/…/gestures/monodrag.dart:236
> > > ...
> > > Handler: "onDown"
> > > Recognizer: VerticalDragGestureRecognizer#e028f
> > >     start behavior: start
> > > ```
> > > 
> > > 
> > > Is there a fix for this from what you know? Thanks
> > 
> > 
> > I have the same problem, did you fix it?
> 
> same here. anyone found a fix?

I can suggest [DraggableScrollableSheet](https://api.flutter.dev/flutter/widgets/DraggableScrollableSheet-class.html) class. Which is developed by flutter team. You can do the same animations with it.

**Comment by fremfi** [comment]
> I can suggest [DraggableScrollableSheet](https://api.flutter.dev/flutter/widgets/DraggableScrollableSheet-class.html) class. Which is developed by flutter team. You can do the same animations with it.

i tried it out, but the only thing is that they don't provide the controller to programatically change the extent, am sure they would in a future update maybe

**Comment by akshathjain** [comment]
This issue is still being worked on. My best timeline for a fix is most likely going to be late-December or early January.

**Comment by osamabinishrat** [comment]
I have found a work around to fix above bug. Just replace following piece of code:
`sc.addListener((){
      setState((){
        if(_sc.offset <= 0) {
          disableScroll = _sc.offset <= 0;
          _pc.close();
        }
      });
    });
`

` onPanelOpened: (){
                setState(() {
                  disableScroll = false;
                  _sc.animateTo(0.1,  curve: Curves.easeOut,
                      duration: const Duration(milliseconds: 100));
                });
              },`

**Comment by akshathjain** [comment]
@osamabinishrat good fix! Ideally, however, the panel should be able to track your finger as you close the panel.

**Comment by akshathjain** [comment]
I've found a solution that provides really good results:
The issues described by @rydrdev, @semsturgut, and @fremfi is related to https://github.com/flutter/flutter/issues/12712 and https://github.com/flutter/flutter/issues/14452. The issue doesn't affect performance, but will be dealt with before this is released. 

I'll most likely clean this up and push to master within the next week or so.
```dart

import 'package:flutter/material.dart';
import 'package:sliding_up_panel/sliding_up_panel.dart';

void main() => runApp(Playground());

class Playground extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      title: 'Playground',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: HomePage(),
    );
  }
}

class HomePage extends StatefulWidget {
  @override
  _HomePageState createState() => _HomePageState();
}


class _HomePageState extends State<HomePage> {

  ScrollController _sc = new ScrollController();
  PanelController _pc = new PanelController();
  bool disableScroll = true;
  bool panelOpen = false;

  @override
  void initState() {
    super.initState();
  }

  @override
  Widget build(BuildContext context){
    return Material(
      child: SlidingUpPanel(
        backdropTapClosesPanel: false,
        panel: Listener(
          onPointerMove: (PointerMoveEvent p){
            if(panelOpen && _sc.offset <= 0){
              setState(() {
                if(p.delta.dy < 0){
                  disableScroll = false;
                }else{
                  disableScroll = true;
                }
              });
            }
          },
          child: _panel(),
        ),
        controller: _pc,
        maxHeight: MediaQuery.of(context).size.height * .80,
        minHeight: 200.0,
        backdropEnabled: true,
        onPanelOpened: (){
          setState(() {
            disableScroll = false;
            panelOpen = true;
          });
        },
        onPanelClosed: (){
          setState(() {
            disableScroll = true;
            panelOpen = false;
          });
        },
      ),
    );
  }

  Widget _panel(){
    return ListView.builder(
      itemCount: 50,
      controller: _sc,
      physics: disableScroll ? NeverScrollableScrollPhysics() : ClampingScrollPhysics(),
      itemBuilder: (BuildContext context, int i){
        return Container(
          padding: const EdgeInsets.all(12.0),
          child: Text("$i"),
        );
      },
    );
  }

}
```

**Comment by j05u3** [comment]
> I've found a solution that provides really good results:
> 
> The issue described by @rydrdev, @semsturgut, and @fremfi is related to [flutter/flutter#12712](https://github.com/flutter/flutter/issues/12712) and [flutter/flutter#14452](https://github.com/flutter/flutter/issues/14452). The issue doesn't affect performance, but will be dealt with before this is released.
> 
> I'll most likely clean this up and push to master within the next week or so.
> 
> ```dart
> import 'package:flutter/material.dart';
> import 'package:sliding_up_panel/sliding_up_panel.dart';
> 
> void main() => runApp(Playground());
> 
> class Playground extends StatelessWidget {
>   @override
>   Widget build(BuildContext context) {
>     return MaterialApp(
>       debugShowCheckedModeBanner: false,
>       title: 'Playground',
>       theme: ThemeData(
>         primarySwatch: Colors.blue,
>       ),
>       home: HomePage(),
>     );
>   }
> }
> 
> class HomePage extends StatefulWidget {
>   @override
>   _HomePageState createState() => _HomePageState();
> }
> 
> 
> class _HomePageState extends State<HomePage> {
> 
>   ScrollController _sc = new ScrollController();
>   PanelController _pc = new PanelController();
>   bool disableScroll = true;
>   bool panelOpen = false;
> 
>   @override
>   void initState() {
>     super.initState();
>   }
> 
>   @override
>   Widget build(BuildContext context){
>     return Material(
>       child: SlidingUpPanel(
>         backdropTapClosesPanel: false,
>         panel: Listener(
>           onPointerMove: (PointerMoveEvent p){
>             if(panelOpen && _sc.offset <= 0){
>               setState(() {
>                 if(p.delta.dy < 0){
>                   disableScroll = false;
>                 }else{
>                   disableScroll = true;
>                 }
>               });
>             }
>           },
>           child: _panel(),
>         ),
>         controller: _pc,
>         maxHeight: MediaQuery.of(context).size.height * .80,
>         minHeight: 200.0,
>         backdropEnabled: true,
>         onPanelOpened: (){
>           setState(() {
>             disableScroll = false;
>             panelOpen = true;
>           });
>         },
>         onPanelClosed: (){
>           setState(() {
>             disableScroll = true;
>             panelOpen = false;
>           });
>         },
>       ),
>     );
>   }
> 
>   Widget _panel(){
>     return ListView.builder(
>       itemCount: 50,
>       controller: _sc,
>       physics: disableScroll ? NeverScrollableScrollPhysics() : ClampingScrollPhysics(),
>       itemBuilder: (BuildContext context, int i){
>         return Container(
>           padding: const EdgeInsets.all(12.0),
>           child: Text("$i"),
>         );
>       },
>     );
>   }
> 
> }
> ```

I tested it in my android emulator and in a real iOS device. For some reason it doesn't work as well (and the bug persists) in my iOS device. I will perform more testing anyway.

**Comment by akshathjain** [comment]
@j05u3 Did you try running it in release mode? Also by doesn’t work well do you mean that it’s laggy or something else? I’m going to test this further on physical devices, but my experience on an iPhone 11 emulator was fairly positive.

**Comment by j05u3** [comment]
> @j05u3 Did you try running it in release mode? Also by doesn’t work well do you mean that it’s laggy or something else? I’m going to test this further on physical devices, but my experience on an iPhone 11 emulator was fairly positive.

No, I only tried in debug mode. I meant that this (https://github.com/akshathjain/sliding_up_panel/issues/17#issuecomment-545912374) keeps happening. I hope I can do further testing one of this days, I am a little busy with other stuff.

**Comment by akshathjain** [comment]
There's a version that's live on the dev branch that doesn't have the bug described here: https://github.com/akshathjain/sliding_up_panel/issues/17#issuecomment-545912374. 

Feel free to check it out (I'm still working on documentation, but the example has been updated).

Here's a quick example demonstrating how to use it:

```dart
import 'package:flutter/material.dart';
import 'package:sliding_up_panel/sliding_up_panel.dart';

void main() => runApp(Playground());

class Playground extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      title: 'Playground',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: HomePage(),
    );
  }
}

class HomePage extends StatefulWidget {
  @override
  _HomePageState createState() => _HomePageState();
}


class _HomePageState extends State<HomePage>{
  @override
  Widget build(BuildContext context) {
    return Material(
      child: SlidingUpPanel(
        backdropTapClosesPanel: true,
        body: Center(child: Text("Linked Scrolling Example")),
        panelBuilder: (sc){
          return ListView.builder(
            itemCount: 50,
            controller: sc,
            itemBuilder: (BuildContext context, int i){
              return Container(
                padding: const EdgeInsets.all(12.0),
                child: Text("$i"),
              );
            },
          );
        },
        maxHeight: MediaQuery.of(context).size.height * .80,
        minHeight: 200.0,
        backdropEnabled: true
      ),
    );
  }
}
```

**Comment by osamabinishrat** [comment]
> ```dart
> panelOpen = false;
> ```

@j05u3 Try this

`onPointerMove: (PointerMoveEvent p) {
                    if (panelOpen && _sc.offset <= 0 && p.delta.dy>10) {
                      _pc.close();
                    }
                  },`

**Comment by akshathjain** [comment]
This functionality has now been released.

**Comment by j05u3** [comment]
@akshathjain  You were right, I think I didn't compile correctly. I just tested in my iOS device and it works fine.

**Comment by akshathjain** [comment]
@j05u3 Did you test using the method described in https://github.com/akshathjain/sliding_up_panel/issues/17#issuecomment-576897143 or using the `v1.0.0`? The most recent update uses a slightly different fix than what's described in the comment.

**Comment by j05u3** [comment]
@akshathjain  I only tried the method described in https://github.com/akshathjain/sliding_up_panel/issues/17#issuecomment-576897143

Awesome, I will try v1.0.0 then.

@osamabinishrat sorry didn't have time to test your solution.
