### ISSUE TITLE
Space area appear at the top of sliding up panel when extendBodyBeheindAppBar is set to true

### ISSUE THREAD

**Issue by fish-like-mammal** [akshathjain/sliding_up_panel#178]
Hi. I am trying to set up a page with a background image, a transparent appbar on top of it and a sliding up panel in my app.
However, when I set extendBodyBehindAppBar to true in the parental Scaffold Widget, there appears a space area at the top of the sliding up panel.
My code: 
`class Example extends StatelessWidget {`
`@override`
`  Widget build(BuildContext context) {`
`    return Scaffold(`
`      extendBodyBehindAppBar: true,`
`      appBar: AppBar(`
`        backgroundColor: Colors.transparent,`
`        elevation: 0,`
`        leading: IconButton(`
`            icon: Icon(Icons.arrow_back),`
`            onPressed: () => Navigator.pop(context)),`
`        actions: <Widget>[`
`          IconButton(icon: Icon(Icons.share), onPressed: () {})`
`        ],`
`      ),`
`      body: SlidingUpPanel(`
`        minHeight: screenHeight - 250,`
`        maxHeight: screenHeight,`
`        borderRadius: BorderRadius.only(`
`          topLeft: Radius.circular(24.0),`
`          topRight: Radius.circular(24.0),`
`        ),`
`        panelBuilder: (sc) => ListView(children: <Widget>[`
`          Container(`
`            child: Column(`
`          children: [`
`            Container(`
`              width: 30,`
`              height: 5,`
`              decoration: BoxDecoration(`
`                  color: Colors.grey[300],`
`                  borderRadius: BorderRadius.all(Radius.circular(12.0))),`
`            ),`
`            SizedBox(height: 10),`
`          ],`
`        ))`
`        ],),`
`        color: contentWhite,`
`        body: ColorFiltered(`
`            colorFilter: ColorFilter.mode(`
`              Colors.black.withOpacity(0.15),`
`              BlendMode.darken,`
`            ),`
`            child: Container(color: Colors.blue,),)`
`      )`
`    );`
`  }`
`}`
Result: 
![Screenshot](https://user-images.githubusercontent.com/51039839/89985333-7cd4df80-dcad-11ea-9617-d279d57d5068.png)

**Comment by fish-like-mammal** [comment]
I temporarily solved this by putting the appbar into the scaffold body wrapped with a Stack widget, yet if anyone still feel concerned about the space area appeared when extendBodyBehindAppBar is set true and appBar in Scaffold is not null this issue is for you.

**Comment by AliRezaBeitari** [comment]
Reopened again. I have the same issue! Is there any way to set `extendBodyBehindAppBar: true` in `Scaffold` without having that extra space on top of panel?
