### ISSUE TITLE
The Collapsed Widget is still interactive yet invisible when the panel is open.

### ISSUE THREAD

**Issue by MasiaVittorio** [akshathjain/sliding_up_panel#19]
If your collapsed widget has any type of gesture detector you won't be able to interact with the top part of the panel. It should be just wrapped inside a conditional IgnorePointer.

**Comment by akshathjain** [comment]
@MasiaVittorio Can you post the code you ran that reproduces this issue?

**Comment by MasiaVittorio** [comment]
I checked again and it doesn't depend on what you have on the collapsed widget. It will always cover the top part of the panel making it impossible to interact with:

In this example tapping on the collapsed widget opens the panel (it works), but tapping on the top part of the panel won't do anything since the collapsed widget covers that part. 

`        return SlidingUpPanel(
          body: Container(color: Colors.white),
          collapsed: GestureDetector(
            onTap: _pc.open,
            child: Container(height: 50, color: Colors.blue,)
          ),
          panel: Column(children: <Widget>[
            GestureDetector(
              onTap: _pc.close,
              child: Container(height: 50, color: Colors.red,)
            )
          ],),
          controller: _pc,
          backdropEnabled: true,
          maxHeight: 500,
          minHeight: 50,
        );
`

**Comment by MasiaVittorio** [comment]
This can be easily fixed by wrapping the collapsed widget under a IgnorePointer with an ignoring parameter that is true only when the panel is fully open

**Comment by akshathjain** [comment]
Good catch! I've fixed the issue and it'll be incorporated into the next release. https://github.com/akshathjain/sliding_up_panel/commit/1aedf2ce2f97431825612278cd3680ab3c9d60d2

**Comment by luciano-work** [comment]
There is a bug with this feature. When I open the panel and change something like an image, the widget is rebuild and the property **_isPanelOpen** is set to **True** and if I close the panel the property istill true, blocking GestureDetector in collapsed

**Comment by rootd** [comment]
This bug still exists.

**Comment by 0xPatryk** [comment]
Its an old thread but you have saved my day :D @MasiaVittorio
