### ISSUE TITLE
Compilation error against dev flutter channel (gestures -> VelocityTracker)

### ISSUE THREAD

**Issue by dcchristopher** [akshathjain/sliding_up_panel#198]
**Describe the bug**
The invocation of Flutter gestures library code (VelocityTracker) from within sliding_up_panel is causing a compilation error due to a breaking change (dev channel for now).

**To Reproduce**
Switch to the dev Flutter channel and `flutter build`

**Expected behavior**
I expect the compilation to succeed.

**Screenshots**
N/A

**Additional context**
Compilation error message:
../../../.pub-cache/hosted/pub.dartlang.org/sliding_up_panel-1.0.2/lib/src/panel.dart:218:44: Error: Too few positional arguments: 1 required, 0 given.

  VelocityTracker _vt = new VelocityTracker();
                                           ^

flutter/packages/flutter/lib/src/gestures/velocity_tracker.dart:152:3: Context: Found this candidate, but the arguments don't match.

  VelocityTracker(this.kind);
  ^^^^^^^^^^^^^^^

FAILURE: Build failed with an exception.

**Smartphone (please complete the following information):**
 - Flutter Version 1.22.0-12.0.pre
 - sliding_up_panel Version 1.0.2

```
```

**Comment by dcchristopher** [comment]
I'd like to note that this is more of a heads up for folks regarding a potential issue with an upcoming release of Flutter. If this dev code is merged into stable, sliding_up_panel will likely cease to work unless a fix is introduced. I realize this isn't an issue with sliding_up_panel with the current stable channel of Flutter.

**Comment by akshathjain** [comment]
I think the current version of Flutter might already be causing issues. Closing this issue and moving the discussion over to #193.

**Comment by dcchristopher** [comment]
> I think the current version of Flutter might already be causing issues. Closing this issue and moving the discussion over to #193.

Gotcha, I’m so sorry I didn’t see that one as a possibility of being related (runtime vs compile time). I should have checked the details.
