### ISSUE TITLE
A callback is needed for onOpen and onClose in order to make other parts of the app reactive.

### ISSUE THREAD

**Issue by MasiaVittorio** [akshathjain/sliding_up_panel#20]
If you want a particular section of the body, or your FloatingActionButton to be reactive to whether the panel is closed or not, you need either to have some stream or listener from the panelController to retrieve the panel state, or at least a basic onOpen / onClose callback to work with.

**Comment by akshathjain** [comment]
Good point! This is currently in works and will be out in the next release. I'm going to close this issue since this same functionality is referenced in #10.
