### ISSUE TITLE
SingleChildScrollView doesn't work inside of panel widget

### ISSUE THREAD

**Issue by Hasankanso** [akshathjain/sliding_up_panel#213]
Hello,

I just used SingleChildScrollView as a value of panel attribute, and I got bad behaviour, just to mention, SingleChildScrollView does not take scrollController as parameter, therefor I'm not sure if it's usable in panelBuilder,

any suggestions? I don't have a list, just some textfields I want to display.

**Comment by salahzsh** [comment]
How did you solve it?
