### ISSUE TITLE
[Feature request] Null safety

### ISSUE THREAD

**Issue by peterscodee** [akshathjain/sliding_up_panel#223]
This is a request to add support for null safety to this package. 
See the [migration guide](https://dart.dev/null-safety/migration-guide) for details about enabling null safety.

**Comment by Vofchuk** [comment]
This is a really big and heavy used package, does anyone knows when will it be null safe?

**Comment by nehal076** [comment]
+1 
Please add null safety

**Comment by ervindobri** [comment]
+1 This is a very heavy package, project depending on it. Please add null safety support

**Comment by bohrasankalp** [comment]
+1

**Comment by VinayakKapur** [comment]
+1

**Comment by ffamar** [comment]
+1

**Comment by mrinaljain** [comment]
+1

**Comment by RandalSchwartz** [comment]
Do you want any help with this? Do you already have a branch started for null-safety that I can add to?

**Comment by akshathjain** [comment]
Hey all, I've merged #230 into the `dev/null-safety` branch. I'll keep it there for a little while to iron out any bugs that may exist, then I'll push the changes to pub.

**Comment by darmawan01** [comment]
wait for it in pub. thanks guys :pray:

**Comment by enricobenedos** [comment]
Hello @akshathjain,
to avoid people to open new issues about the null safety topic I advice you to pin this issue on order to find it more simply 😉

**Comment by ludwiktrammer** [comment]
@akshathjain When do you plan release a stable version with null safety support?

**Comment by wilk3ns** [comment]
+1

**Comment by akshathjain** [comment]
I'll try to release this over the weekend.

**Comment by Vofchuk** [comment]
Let us know wen you update it

**Comment by mrkevinomar** [comment]
Hello @akshathjain, any update?

**Comment by lt692** [comment]
+1

**Comment by ctedgar** [comment]
+1

**Comment by ervindobri** [comment]
+1

**Comment by akshathjain** [comment]
Hey all, v2.0.0 should be live on pub now with null safety support :)

Please feel free to create new issues if anything seems broken.

**Comment by edytk** [comment]
thanks @akshathjain 🙏
