### ISSUE TITLE
Package does not work with latest version of flutter and dart

### ISSUE THREAD

**Issue by godwintrav** [akshathjain/sliding_up_panel#241]
**Describe the bug**
This package does not work with the new flutter sdk version and new dart sdk version

**To Reproduce**
Please make the package work with the new sdk versions

**Expected behavior**
I expect this package to be able to build and compile with the flutter latest sdk version without crashing the app

**Screenshots**

**Additional context**

**Smartphone (please complete the following information):**
 - Flutter Version [e.g. 1.12.13]
 - sliding_up_panel Version [e.g. 1.0.0]

**Sample `main.dart`**
Please provide a sample `main.dart` that reproduces this issue. The code provided here should be able to be run on its own without any external dependencies.
```
```

**Comment by akshathjain** [comment]
See #223
