### ISSUE TITLE
In release mode weird first few frames flicker on iOS (more obvious on old devices)

### ISSUE THREAD

**Issue by Nazacheres** [akshathjain/sliding_up_panel#27]
As in other similar libraries, this one has that issue, that the size is defined by `MediaQuery.of(context).size.width` and on the very beggining the issue that may happen is that there is no width defined, or it's wrong. And the process of calculating this value differs in release and debug modes. Issue also reproducable with the example provided. It is obvious on iPhone 5s and pretty noticable on iPhone 6 and family.

**Comment by akshathjain** [comment]
@Nazacheres I unfortunately don't have any of the phones you mentioned to test this on (besides the emulators, which can't run release mode), so I'm unable to reproduce the issue. This seems more like a Flutter issue than anything else. I would recommend opening this issue in the Flutter repo so it gets more attention.
