### ISSUE TITLE
close panel when i press on back 

### ISSUE THREAD

**Issue by MahdiPishguy** [akshathjain/sliding_up_panel#31]
how can i close panel when i press on back button on phone?

this code don't work

```
class _LoginForm extends State<LoginForm> with SingleTickerProviderStateMixin {
  PanelController _pc = new PanelController();

...

return WillPopScope(
  onWillPop: () {
    if(_pc.isPanelShown()){
      _pc.hide();
    }
  },
  child: Scaffold(
```

**Comment by akshathjain** [comment]
`_pc.hide()` should be replaced with `_pc.close()`.

Here is a sample `main.dart`:

```dart
import 'package:flutter/material.dart';
import 'package:sliding_up_panel/sliding_up_panel.dart';

void main() => runApp(Playground());

class Playground extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      title: 'Playground',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: HomePage(),
    );
  }
}

class HomePage extends StatefulWidget {
  @override
  _HomePageState createState() => _HomePageState();
}


class _HomePageState extends State<HomePage> {
  PanelController _pc = new PanelController();

  Widget build(BuildContext context){
    return WillPopScope(
      onWillPop: _onWillPop,
      child: Material(
        child: SlidingUpPanel(
          panel: Center(child: Text("Panel")),
          body: Center(child: Text("Body"),),
          collapsed: Container(color: Colors.orange,),
          parallaxEnabled: true,
          controller: _pc,
        )
      ),
    );
  }

  Future<bool> _onWillPop() async{
    if(_pc.isPanelOpen()){
      _pc.close();
      return false;
    }else{
      return true;
    }
  }

}
```

**Comment by federicodesia** [comment]
> `_pc.hide()` should be replaced with `_pc.close()`.
> 
> Here is a sample `main.dart`:
> 
> ```dart
> import 'package:flutter/material.dart';
> import 'package:sliding_up_panel/sliding_up_panel.dart';
> 
> void main() => runApp(Playground());
> 
> class Playground extends StatelessWidget {
>   @override
>   Widget build(BuildContext context) {
>     return MaterialApp(
>       debugShowCheckedModeBanner: false,
>       title: 'Playground',
>       theme: ThemeData(
>         primarySwatch: Colors.blue,
>       ),
>       home: HomePage(),
>     );
>   }
> }
> 
> class HomePage extends StatefulWidget {
>   @override
>   _HomePageState createState() => _HomePageState();
> }
> 
> 
> class _HomePageState extends State<HomePage> {
>   PanelController _pc = new PanelController();
> 
>   Widget build(BuildContext context){
>     return WillPopScope(
>       onWillPop: _onWillPop,
>       child: Material(
>         child: SlidingUpPanel(
>           panel: Center(child: Text("Panel")),
>           body: Center(child: Text("Body"),),
>           collapsed: Container(color: Colors.orange,),
>           parallaxEnabled: true,
>           controller: _pc,
>         )
>       ),
>     );
>   }
> 
>   Future<bool> _onWillPop() async{
>     if(_pc.isPanelOpen()){
>       _pc.close();
>       return false;
>     }else{
>       return true;
>     }
>   }
> 
> }
> ```


This only works for collapsing the panel when pressing the back button.

But `WillPopScope` is preventing closing the application when the panel is not open.

Any solution for this?
