### ISSUE TITLE
How to programmingly open and close SlidingUpPanel

### ISSUE THREAD

**Issue by huzhiren** [akshathjain/sliding_up_panel#32]
`SlidingUpPanel` is awesome.   But I don't know how to programmingly open and close `SlidingUpPanel`. Any idea?

**Comment by huzhiren** [comment]
Oh, I found it,  by providing a controller, then call open and close.  But isPanelOpen() will throw error in build() function:

NoSuchMethodError: The method 'call' was called on null.
Receiver: null
Tried calling: call()
#0      Object.noSuchMethod (dart:core/runtime/libobject_patch.dart:50:5)
#1      PanelController.isPanelOpen (package:sliding_up_panel/src/panel.dart:539:12)

**Comment by akshathjain** [comment]
@huzhiren This is intended. The `PanelController` is an object that returns information about the state / modifies the state of the `SlidingUpPanel`. As a result, if you try to call `PanelController` methods before its attached to a `SlidingUpPanel` (like in the build method when the `SlidingUpPanel` is being built), you will get an error, as the panel doesn't exist yet (i.e. the first iteration of the build method when the panel hasn't been built).

**Comment by huzhiren** [comment]
Yes, that's fine. I end up with a boolean in status to track if the `SlidingUpPanel` is open or not.
I think it would be best if the `initial height` or constraint with min/max height (there is another issue saying `default height`) can adapt to the content of the panel. Currently you have to specify min/max height, otherwise, there is a default 100/500 there.
