### ISSUE TITLE
Close panel when keyboard is open

### ISSUE THREAD

**Issue by Damix48** [akshathjain/sliding_up_panel#33]
It would be useful to add the option for close automatically the panel when the keyboard is open.
As show in the screenshot the panel is above the keyboard. When the panel is fully opened and a TextField is focused the panel obscure all the view.

not-fully opened
![screenshot](https://user-images.githubusercontent.com/23702345/58746912-41614300-8464-11e9-808f-c99b78626e1a.jpeg)

fully opened 
![screenshot 2](https://user-images.githubusercontent.com/23702345/58746964-cb111080-8464-11e9-8fb0-ada84db6678f.jpeg)

**Comment by akshathjain** [comment]
@Damix48 This is a very specific feature and can vary from use-case to use-case, so it probably won't be added directly into the library. However, you can still close the panel when the keyboard is open by attaching a `PanelController _pc` to your `SlidingUpPanel` and calling `_pc.close()` when the keyboard is opened.
