### ISSUE TITLE
Adding Opacity

### ISSUE THREAD

**Issue by gibranramadhan** [akshathjain/sliding_up_panel#34]
What about adding features to adjust opacity? I think that will help people who want to use gradient background

**Comment by akshathjain** [comment]
You should be able to adjust the color property. E.g.: 
```
SlidingUpPanel(
   color: Color.fromARGB(0,0,0,0),
   panel: Container(),
   body: Container()
)
```
Would be a completely transparent panel.

**Comment by gibranramadhan** [comment]
it still gives a shadow effect (or elevation I guess)

**Comment by akshathjain** [comment]
Try using the `boxShadows` property to change how those appear.
