### ISSUE TITLE
Allow to add listeners to a PanelController

### ISSUE THREAD

**Issue by ofekashery** [akshathjain/sliding_up_panel#36]
For the ``onPanelSlide`` , ``onPanelClosed`` and ``onPanelOpened``.

For example:
```dart
PanelController pc = PanelController();
pc.addOnPanelSlideListener((double position){
  print(position);
});
```

**Comment by mausamRayamajhi** [comment]
I was also looking for this "Listener" method when panel PanelPosition changed.
But, I only found getPanelPosition(),
hope, it will be added

**Comment by akshathjain** [comment]
@ofekashery Unfortunately, any listeners attached to the PanelController have to be attached after the PanelController is attached to a sliding up panel. As a result, the code you've provided would have to be nested after the SlidingUpPanel is already rendered in the build method. The cleanest solution would be to use the onPanelSlide property of the SlidingUpPanel.
