### ISSUE TITLE
How to Scroll along with List inside pannel

### ISSUE THREAD

**Issue by mausamRayamajhi** [akshathjain/sliding_up_panel#38]
I want similar behavor like samsung app store .. it scroll pannel with list. How can we do that?

Video link is provided =>
https://www.facebook.com/carloseugeniotorres/videos/2239865416068500/

**Comment by mausamRayamajhi** [comment]
I think this is the solution...may be not best. but it works

![1](https://user-images.githubusercontent.com/28975010/60766903-ba8d2f00-a0cf-11e9-8664-02c4ad962f6d.png)
![2](https://user-images.githubusercontent.com/28975010/60766904-bb25c580-a0cf-11e9-8135-c014b7465a3a.png)
![3](https://user-images.githubusercontent.com/28975010/60766905-bb25c580-a0cf-11e9-97bf-084bd9cd051c.png)

**Comment by Fabi755** [comment]
Have a look at [DraggableScrollableSheet](https://api.flutter.dev/flutter/widgets/DraggableScrollableSheet-class.html). This is much easier without a work arround :-)

**Comment by sooxiaotong** [comment]
this still buggy anyway...

**Comment by rituapplocum** [comment]
How to implement Scroll to index here. As it won't scroll the list if data is beyond the sliding panel.
