### ISSUE TITLE
Perfomance is not 60 fps

### ISSUE THREAD

**Issue by EDnny12** [akshathjain/sliding_up_panel#39]
Can you update for better perfomance?

Thanks

**Comment by akshathjain** [comment]
@EDnny12 Can you provide some details to what phone / OS / OS version you were using when you tested this?

**Comment by EDnny12** [comment]
With Android 9.0

**Comment by Bennet303** [comment]
I had similar issues when testing in debug mode but the performance problem was eventually fixed when launching the app in release mode (flutter run --release)

**Comment by akshathjain** [comment]
@EDnny12 can you try testing on a physical device with `release` mode like @Bennet303 mentions? This might solve the issue. Let me know if the problem still persists.

**Comment by dvlj** [comment]
performance is always bad in debug mode compare to release mode, try not to judge the result in debug mode.
