### ISSUE TITLE
Example with Provider for PanelController State Management

### ISSUE THREAD

**Issue by hectorAguero** [akshathjain/sliding_up_panel#40]
So, currently i'm use this plugin and I need to manage the controller from other class, so I'm sharing this public example for anyone who wants to use  https://github.com/hectorAguero/slidingpanelexample

Currently I'm works with some similar in a app, but after call a PageRoute(LoginPage to HomePage), I have problems with the controller inside the model class , I don't put that code in the example because I dont have more time now, so all the example works.

The code, doesn't have comments, sorry for that.

Any comment is welcomed

![GIF](https://i.imgur.com/5a6zwze.gif)

**Comment by akshathjain** [comment]
Nice, I like it!

**Comment by akshathjain** [comment]
Closing this issue, but will be updating the documentation to include your project in a tutorials section.
