### ISSUE TITLE
[Feature Request] AnimatedContainer in place of Container?

### ISSUE THREAD

**Issue by Nolence** [akshathjain/sliding_up_panel#41]
Hi! Really love the package! What are your thoughts on making the [container here](https://github.com/akshathjain/sliding_up_panel/blob/3c38a55f0a070738c88b18349d4b3c54aa5b23b6/lib/src/panel.dart#L240) an AnimatedContainer?

I have the use case where my panel can hava data in it or be empty (it's holding a sport player's information). The user can click on a player in main UI list to fetch the data and on load I wanted the panel to animate up to a minimum height of 60 (whereas it's empty value is 40). Using setState and animated container, it's as simple as changing the minHeight property on the `SlidingUpPanel`:

```dart
minHeight: playerSummary?.player == null ? 40 : 60,
```

**Comment by akshathjain** [comment]
This is an interesting idea - I'll play around with it and see how it impacts performance (if any). In the meantime, the `PanelController` can be used to achieve a similar effect.

**Comment by Nolence** [comment]
Cool, completely overlooked using the controller. I'll look into that when  get the time. Thanks!

**Comment by akshathjain** [comment]
I'm going to go ahead and close this issue. I think replacing the Container with an AnimatedContainer at this point would cause a breaking change that can be avoided by using the PanelController.

**Comment by RomanJos** [comment]
Hello, do you think you can explain a bit more on this ? I'm in the same situation.
