### ISSUE TITLE
Accessibility support (Talkback)

### ISSUE THREAD

**Issue by pdmshrestha** [akshathjain/sliding_up_panel#42]
Hi,
Thanks for great package. Has anyone notice that Talkback behaves weird with sliding panel. The body widget is hard to focus. I have a listview widget in the sliding panel body. When I focus on the listview, it doesn't get focused, however if I swipe right it goes through the list.

**Comment by akshathjain** [comment]
@pdmshrestha Could you provide a sample `main.dart` file that reproduces the issue, as well as steps to reproduce the issue with Talkback?

**Comment by akshathjain** [comment]
Going ahead and closing this issue due to lack of response.

**Comment by AndroidNils** [comment]
I opened a new ticket with a demo + sample code in #168 👍
