### ISSUE TITLE
Borders will not round properly

### ISSUE THREAD

**Issue by aedaia** [akshathjain/sliding_up_panel#46]
Hi,

I am unable to get the borders to round correctly on my application. Instead, it creates a colour that matches my background colour to fill the corners with.

**Comment by akshathjain** [comment]
Hi, could you attach your `main.dart` and a screenshot of the issue you're seeing?

**Comment by aedaia** [comment]
Hi! 

This is our code:



We are also having issues hiding the bottom navbar when we swipe up on the panel - is there a way to hide this?



Kind regards,
Eden.

**Comment by akshathjain** [comment]
I don't think your code uploaded properly, can you try copy/pasting it into the response?

**Comment by aedaia** [comment]
Of course,

import 'package:flutter/material.dart';
import 'bottomTabBar.dart';
import 'package:sliding_up_panel/sliding_up_panel.dart';
import 'camera.dart';
import 'package:camera/camera.dart';

class RewardPlaceHolder extends StatelessWidget {
  final String imagePath;

  RewardPlaceHolder({
    this.imagePath,
  });

  @override
  Widget build(BuildContext context) {
    return Container(
      padding: EdgeInsets.only(left: 10, right: 10),
      child: Image.asset(
        imagePath,
        width: 150,
        height: 150,
      ),
    );
  }
}

class StatisticPlaceHolder extends StatelessWidget {
  final String number, object;
  final Color bgColor;
  StatisticPlaceHolder({this.number, this.object, this.bgColor});
  @override
  Widget build(BuildContext context) {
    return Container(
      margin: EdgeInsets.only(bottom: 20.0, left: 10.0),
      width: 130,
      decoration: BoxDecoration(
          borderRadius: BorderRadius.all(Radius.circular(40.0)),
          color: bgColor),
      child: Column(
        mainAxisAlignment: MainAxisAlignment.center,
        children: <Widget>[
          Container(
            child: Text(
              number,
              style: TextStyle(
                  fontWeight: FontWeight.bold,
                  fontSize: 40,
                  color: Colors.white),
            ),
          ),
          Container(
            child: Text(
              object,
              style: TextStyle(
                fontSize: 15,
                fontWeight: FontWeight.w400,
                color: Colors.white,
              ),
            ),
          ),
        ],
      ),
    );
  }
}

class LandingPage extends StatefulWidget {
  @override
  State<StatefulWidget> createState() {
    return LandingPageState();
  }
}

class LandingPageState extends State<LandingPage> {
  Widget camera;

  Future<Widget> displayCamera() async {
    final cameras = await availableCameras();
    final firstCamera = cameras.first;
    return TakePictureScreen(camera: firstCamera);
  }

  LandingPageState() {
    displayCamera().then((val) => setState(() {
          camera = val;
        }));
  }

  PanelController _pc = new PanelController();

  Widget upperScreen = Stack(children: <Widget>[
    Container(
      color: Color.fromRGBO(65, 65, 65, 1),
    ),
    Container(
        child: Column(
      children: <Widget>[
        Container(
          height: 160,
          decoration: BoxDecoration(
              borderRadius: BorderRadius.only(
                  topLeft: Radius.circular(40.0),
                  topRight: Radius.circular(40.0)),
              color: Color.fromRGBO(0, 164, 227, 1)),
          child: Column(
            children: <Widget>[
              Container(
                alignment: Alignment.center,
                child: new IconButton(
                  iconSize: 7,
                  icon: Icon(
                    IconData(0xe806, fontFamily: 'DraggerIcon'),
                    color: Colors.white,
                  ),
                  onPressed: null,
                ),
              ),
              Container(
                alignment: Alignment.centerLeft,
                padding: EdgeInsets.only(left: 30),
                child: Text(
                  'is it recyclable?',
                  style: TextStyle(
                    fontWeight: FontWeight.bold,
                    fontSize: 30,
                    color: Colors.white,
                  ),
                ),
              ),
              Container(
                alignment: Alignment.centerLeft,
                padding: EdgeInsets.only(
                  left: 30,
                ),
                child: Text(
                  'swipe up to find out',
                  style: TextStyle(
                    fontWeight: FontWeight.w300,
                    fontSize: 23,
                    color: Colors.white,
                  ),
                ),
              ),
            ],
          ),
        ),
      ],
    ))
  ]);

  Widget _body() {}

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: Color.fromRGBO(65, 65, 65, 1),
      body: Stack(
        children: <Widget>[
          ListView(
            children: <Widget>[
              Container(
                  padding: EdgeInsets.only(top: 40, left: 20),
                  color: Color.fromRGBO(65, 65, 65, 1),
                  child: Column(
                    crossAxisAlignment: CrossAxisAlignment.start,
                    children: <Widget>[
                      Text(
                        'Hello,',
                        style: TextStyle(
                          color: Colors.white,
                          fontWeight: FontWeight.w300,
                          fontSize: 49,
                        ),
                      ),
                      Text(
                        'Anna',
                        style: TextStyle(
                            color: Colors.white,
                            fontWeight: FontWeight.bold,
                            fontSize: 49),
                      )
                    ],
                  )),
              Container(
                height: 350,
                color: Color.fromRGBO(65, 65, 65, 1),
                child: ListView(
                  scrollDirection: Axis.horizontal,
                  children: <Widget>[
                    GeneralFactPlace(),
                    GeneralFactPlace(),
                    GeneralFactPlaceLast(),
                  ],
                ),
              ),
            ],
          ),
          SlidingUpPanel(
            borderRadius: BorderRadius.only(
                topLeft: Radius.circular(40.0),
                topRight: Radius.circular(40.0)),
            minHeight: 160,
            maxHeight: 1000,
            collapsed: upperScreen,
            panel: camera,
          )
        ],
      ),
      bottomNavigationBar: BottomTabBar(
        bgColor: Color.fromRGBO(0, 164, 227, 1),
      ),
    );
  }
}

class GeneralFactPlace extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Stack(
      alignment: Alignment.bottomCenter,
      children: <Widget>[
        Container(
            alignment: Alignment.centerRight,
            width: 230,
            height: 310,
            margin: EdgeInsets.only(bottom: 10, left: 20),
            decoration: new BoxDecoration(
              color: Color.fromRGBO(65, 65, 65, 1),
              image: new DecorationImage(
                alignment: Alignment.center,
                image: new AssetImage("assets/images/Asset 5b.png"),
              ),
            ),
            child: Column(
              mainAxisAlignment: MainAxisAlignment.center,
              children: <Widget>[
                Container(
                    margin: EdgeInsets.only(top: 145, right: 50),
                    child: Text(
                      'you have prevented ',
                      style: TextStyle(color: Colors.white, fontSize: 15),
                    )),
                Row(
                  children: <Widget>[
                    Container(
                        margin: EdgeInsets.only(left: 20, right: 10),
                        child: Text(
                          '12.3',
                          style: TextStyle(
                              color: Colors.white,
                              fontSize: 35,
                              fontWeight: FontWeight.bold),
                        )),
                    Container(
                        margin: EdgeInsets.only(right: 25),
                        child: Text(
                          'tonnes',
                          style: TextStyle(color: Colors.white, fontSize: 35),
                        )),
                  ],
                ),
                Container(
                    margin: EdgeInsets.only(left: 25, right: 50),
                    child: Text(
                      'of plastic from polluting the ocean',
                      style: TextStyle(color: Colors.white, fontSize: 15),
                    )),
              ],
            )),
      ],
    );
  }
}

class GeneralFactPlaceLast extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Stack(
      alignment: Alignment.bottomCenter,
      children: <Widget>[
        Container(
            alignment: Alignment.centerRight,
            width: 230,
            height: 310,
            margin: EdgeInsets.only(bottom: 10, left: 20, right: 20),
            decoration: new BoxDecoration(
              color: Color.fromRGBO(65, 65, 65, 1),
              image: new DecorationImage(
                alignment: Alignment.center,
                image: new AssetImage("assets/images/Asset 5b.png"),
              ),
            ),
            child: Column(
              mainAxisAlignment: MainAxisAlignment.center,
              children: <Widget>[
                Container(
                    margin: EdgeInsets.only(top: 145, right: 50),
                    child: Text(
                      'you have prevented ',
                      style: TextStyle(color: Colors.white, fontSize: 15),
                    )),
                Row(
                  children: <Widget>[
                    Container(
                        margin: EdgeInsets.only(left: 20, right: 10),
                        child: Text(
                          '12.3',
                          style: TextStyle(
                              color: Colors.white,
                              fontSize: 35,
                              fontWeight: FontWeight.bold),
                        )),
                    Container(
                        margin: EdgeInsets.only(right: 25),
                        child: Text(
                          'tonnes',
                          style: TextStyle(color: Colors.white, fontSize: 35),
                        )),
                  ],
                ),
                Container(
                    margin: EdgeInsets.only(left: 25, right: 50),
                    child: Text(
                      'of plastic from polluting the ocean',
                      style: TextStyle(color: Colors.white, fontSize: 15),
                    )),
              ],
            )),
      ],
    );
  }
}

**Comment by hectorAguero** [comment]
In my example, I need to put the widget wrapped with ThemeData and pass a Colors.transparent in canvascolor to fix this, but if I need to use any color I need to pass the color this

https://github.com/hectorAguero/slidingpanelexample/blob/master/lib/page_two_home.dart


```dart

  final BorderRadiusGeometry radius = BorderRadius.only(
    topLeft: Radius.circular(24.0),
    topRight: Radius.circular(24.0),
  );
  @override
  Widget build(BuildContext context) {
    return SlidingUpPanel(
      borderRadius: radius,
      controller: Provider.of<ModelSliding>(context).panelController,
      maxHeight: MediaQuery.of(context).size.height -
          MediaQuery.of(context).padding.vertical
      minHeight: 52,
      body: Container(
        color: Colors.lime,
        child: Center(
          child: Text("My Panel Slide Down"),
        ),
      ),
      panel: Theme(
          data: ThemeData(
            canvasColor: Colors.transparent,
            accentColor: Colors.yellow,
          ),
          child: PageTwoSliding()),
      collapsed: Theme(
        data: ThemeData(
          canvasColor: Colors.transparent,
          accentColor: Colors.yellow,
        ),
        child: YourCollapsedChildWidget()
