### ISSUE TITLE
Body is covered by collapsed slide up panel

### ISSUE THREAD

**Issue by YaarPatandarAA** [akshathjain/sliding_up_panel#48]
I am using a ListView as body and it is a list of items. However when the panel is collapsed the body is not above the panel. The last item in the ListView is covered by the collapsed panel. 

How can I shift it up so the ListView is above the collapsed panel, as to show the last item?

**Comment by YaarPatandarAA** [comment]
Just Add Padding to the bottom of the ListView as much as the min size of the collapsed panel.

**Comment by johnny-stevie** [comment]
Could you provide some code on how to solve that? I'm a bit confused on how to implement it.

**Comment by ArtemMikhaylov** [comment]
I don't know why, but in my case, to make visible last item of ListView with panel in the collapsed state, I needed to add padding to the bottom of the ListView as much as the MAX height of the panel. And in case if I have also bottom navigation bar, I had to add `kBottomNavigationBarHeight` to padding as well.
