### ISSUE TITLE
Set default state to open?

### ISSUE THREAD

**Issue by yuankunluo** [akshathjain/sliding_up_panel#49]
Hi, how can we set the default pannel to be opened;

I use this Widget as my Home page which i need to open this Pannel as default.

So how can we set it?

**Comment by akshathjain** [comment]
@yuankunluo I can see this as being a pretty important feature. Will definitely add in the next release.

**Comment by akshathjain** [comment]
Added the `defaultPanelState` property in v0.3.5. Changes should be live in the next few minutes.
