### ISSUE TITLE
Dark brightness mode in ThemeData vanishes all widgets

### ISSUE THREAD

**Issue by NewITCorp** [akshathjain/sliding_up_panel#53]
Hi, 
The current version has an issue with brightness mode.
steps to reproduce
1. add a dark brightness in your example

return MaterialApp(
      debugShowCheckedModeBanner: false,
      title: 'SlidingUpPanel Example',
      theme: ThemeData(primarySwatch: Colors.blue, **brightness: Brightness.dark**),
      home: HomePage(),
    );

  2. run and get the result like this
https://uppic.cc/d/5v25

all the text is gone. maybe it does not respect the dark mode.

**Comment by NewITCorp** [comment]
Hi, may I ask if you have chance to take a look at this?

**Comment by akshathjain** [comment]
Looks like this was overlooked in the sample app. The container colors aren’t coded to change their colors when the dark theme is turned on.

**Comment by NewITCorp** [comment]
what do you suggest to fix this?
