### ISSUE TITLE
Click panel title to slide up itself without dragging?

### ISSUE THREAD

**Issue by sooxiaotong** [akshathjain/sliding_up_panel#58]

**Comment by akshathjain** [comment]
You can use the `PanelController` to pragmatically control the `SlidingUpPanel`.

 https://github.com/akshathjain/sliding_up_panel#using-the-panelcontroller

**Comment by sooxiaotong** [comment]
Okie thanks

**Comment by sooxiaotong** [comment]
Okie thanks
