### ISSUE TITLE
MaxHeight to wrap content's height

### ISSUE THREAD

**Issue by imchivaa** [akshathjain/sliding_up_panel#61]
Hi there, I have a quick question if there's any wrap panel's content height? I want the panel's height to be dynamic to it's child. I tried to get the height of the panel's child widget then set it to the maxHeight so that when the panel opens, the maxheight will be adjusted but this doesn't work because the widget isn't available yet when the calculation performed.

The only way of doing this is in the onPanelOpened callback to calculate and adjust the height of the panel. The problem here is that the animation it adjusted the new height doesn't look good. It jump to the new height and fix itself in position. Have any ways to achieve this?

Thank you. :)

**Comment by chuabingquan** [comment]
Hello, is there any follow up to this issue? @akshathjain

**Comment by timbrueckner** [comment]
I was looking for the same thing. I think it should behave like HTML. In case no maxHeight was set it should take up just as much space as its content requires. Thanks for the widget! It is really great 👍🏻

**Comment by chounry** [comment]
Did u take a look on flutter BottomSheet.?

**Comment by timbrueckner** [comment]
> Did u take a look on flutter BottomSheet.?

I will give it a try. Thanks for mentioning.

**Comment by fxjordan** [comment]
I think wrapping the panel in a `LayoutBuilder` works.

```Dart
LayoutBuilder(
  builder: (key, builder) => SlidingUpPanel(
    maxHeight: builder.maxHeight,
    panel: Container(
      height: 200,
      color: Colors.green,
    ),
  ),
)
```

**Comment by imchivaa** [comment]
I am closing this since I've moved away from this package. Unless the author responded with a proper way of doing thsi with this package.

**Comment by shahmirzali49** [comment]
@imchivaa  did you solve it?

**Comment by SvehlaJan** [comment]
Hello. Anyone found a way how to achieve this?
The content of my panel is dynamic (there is a ListView which can have 1 to x items). If there is only 1 item (and the content is small), the panel opens only to it's full height (maxHeight) so there is a lot of empty space below my content.
Do I really need to compute the maxHeight dynamically? Thanks.

**Comment by aneshodza** [comment]
Why was this issue closed? The Issue wasn't resolved yet.
