### ISSUE TITLE
Add option to make collapsed panel persist

### ISSUE THREAD

**Issue by SwissCheese5** [akshathjain/sliding_up_panel#63]
The gifs on the pub.dev page are misleading; in google maps, the "Explore <place>" text stays on top and does not transition to close. I needed this behavior, so it would be a great addition.

https://raw.githubusercontent.com/akshathjain/sliding_up_panel/master/screenshots/example.gif

**Comment by akshathjain** [comment]
Hi,

The gifs on pub.dev aren't of Google Maps, its the example implementation of SlidingUpPanel (the source code is in the example directory in this repo). 

Could you also clarify what type of behavior you're looking for?

Thanks!

**Comment by SwissCheese5** [comment]
So, the gifs show the "Explore Pitssburg" text staying after opening the panel, ie: the collapsed panel STAYS on top of the body after opening instead of it fading out. This should be an option :)

**Comment by SwissCheese5** [comment]
Ok so this is possible, you're right. But I would add in the docs that it's possible to not specify a collapsed panel
