### ISSUE TITLE
When Using Panel and Material Drawer. Panel Shows above the drawer

### ISSUE THREAD

**Issue by adim86** [akshathjain/sliding_up_panel#67]
![Simulator Screen Shot - iPhone 11 Pro Max - 2019-10-11 at 11 17 57](https://user-images.githubusercontent.com/170634/66644462-e52fdc00-ec18-11e9-88f4-6cbbbf8874ef.png)

**Comment by viddik13** [comment]
This can happen when `SlidingUpPanel` wraps `Scaffold`. Wrapping the `SlidingUpPanel` with `Scaffold` (the recommended method according to [docs](https://pub.dev/packages/sliding_up_panel#simple-usage)) will make the `Drawer` slide over the `SlidingUpPanel` properly.

Before:
```dart
SlidingUpPanel(
   collapsed: _collapsed(),
   panel: _panel(),
   body: Scaffold(
       key: _drawerKey,
       drawer: _drawer(),
       body: _sliderBody()
    )
)
```

After:
```dart
Scaffold(
  key: _drawerKey,
  drawer: _drawer(),
  body: SlidingUpPanel(
    collapsed: _collapsed(),
    panel: _panel(),
    body: _sliderBody()
  )
)
```

**Comment by akshathjain** [comment]
@viddik13 is correct, that is the recommend solution. Closing.
