### ISSUE TITLE
FadeTransition to handle opacity

### ISSUE THREAD

**Issue by mazei513** [akshathjain/sliding_up_panel#69]
The [Flutter docs](https://api.flutter.dev/flutter/widgets/Opacity-class.html) raises concerns over animating using `Opacity`. When collapsed is used, the animation between collapsed to panel does exactly what the docs warns against. The current code for the collapsed panel is:

      // collapsed panel
      Positioned(
        top: widget.slideDirection == SlideDirection.UP ? 0.0 : null,
        bottom: widget.slideDirection == SlideDirection.DOWN ? 0.0 : null,
        width:  MediaQuery.of(context).size.width -
                (widget.margin != null ? widget.margin.horizontal : 0) -
                (widget.padding != null ? widget.padding.horizontal : 0),
        child: Container(
          height: widget.minHeight,
          child: Opacity(
            opacity: 1.0 - _ac.value,

            // if the panel is open ignore pointers (touch events) on the collapsed
            // child so that way touch events go through to whatever is underneath
            child: IgnorePointer(
              ignoring: _isPanelOpen(),
              child: widget.collapsed ?? Container(),
            ),
          ),
        ),
      ),

**Comment by mazei513** [comment]
Could change `Opacity` to

```
FadeTransition(
  opacity: Tween(begin: 1.0, end: 0.0).animate(_ac),
  child: ...
)
```

**Comment by akshathjain** [comment]
Good catch, will change in the next update.
