### ISSUE TITLE
Panel should have slide-down configuration param

### ISSUE THREAD

**Issue by zacwolfe** [akshathjain/sliding_up_panel#7]
Great work on this great widget! However, I'd love to have the option to drag the panel from the top to the bottom as well.  I'll submit a PR to address this issue now.

**Comment by akshathjain** [comment]
This is definitely an interesting idea! I've taken a look at your PR (#8) and everything seems to work well—great job! 

I've gone ahead and accepted your PR. I'm probably going to make a few changes, but hopefully this feature will be available in the next release (or one shortly afterwards).

**Comment by aytunch** [comment]
@zacwolfe  Great idea👍👍

**Comment by zacwolfe** [comment]
Great, glad I could help!
