### ISSUE TITLE
Is it possible to support custom protruding header? The current requirement is that I need to set a tabbar expansion in the header to be a listview

### ISSUE THREAD

**Issue by jahnli** [akshathjain/sliding_up_panel#71]
I think this is a very good library    ,
Is it possible to support custom protruding header? The current requirement is that I need to set a tabbar expansion in the header to be a listview

![image](https://user-images.githubusercontent.com/20943608/68527688-b5ade580-0324-11ea-98fb-192125fd5cb9.png)

**Comment by jahnli** [comment]
![image](https://user-images.githubusercontent.com/20943608/68528594-d16ab900-032f-11ea-800a-4fd697cae219.png)

我目前能想到的方案是 stack里放置一个tabbar 和一个tabbarview 不知道是否有更好的方案

**Comment by akshathjain** [comment]
`header` and `footer` properties added in v1.0.2.
