### ISSUE TITLE
Panel disappears when keybord on screen?

### ISSUE THREAD

**Issue by xyzbilal** [akshathjain/sliding_up_panel#74]
How to make panel is open even keyboard on screen? thanks..

**Comment by xyzbilal** [comment]
adding `resizeToAvoidBottomInset:  false, `   to scaffold solved my problem.

**Comment by akshathjain** [comment]
Yes, I've encountered this myself and that is the correct fix. Closing this issue.

**Comment by huxaiphaer** [comment]
I added `resizeToAvoidBottomInset: false,` but it's not working. 😢
