### ISSUE TITLE
Panel sometimes disposed and disappeared

### ISSUE THREAD

**Issue by furkansarihan** [akshathjain/sliding_up_panel#76]
I can not trace what cause the problem but panel sometimes disposed and diseppeared and doesn't come back.

I use a StatefulWidget as panel

**Comment by akshathjain** [comment]
Can you attach a sample `main.dart` that replicates this issue?

**Comment by akshathjain** [comment]
Closing due to lack of response. Feel free to reopen this if the issue persists.

**Comment by brianschardt** [comment]
I get this same issue.

@akshathjain when i go back using navigator.pop and then I try and open up the pannel I get this error: 
```
AnimationController.animateTo() called after AnimationController.dispose()
AnimationController methods should not be used after calling dispose.
```
