### ISSUE TITLE
When set direction: SlideDirection.DOWN, panel content is not visible

### ISSUE THREAD

**Issue by wemersonrv** [akshathjain/sliding_up_panel#81]
Hello, great job with this package. Amazing!!!

My question about `SlideDirection.DOWN`. When i set it in directon, the `panel` content is not visible... How can i fix that?

I've tried to wrap content in a new Container, positioned, column, etc... nothing works!

I think i am missing some point.

here my code:
```dart
Widget build(BuildContext context) {
    return SlidingUpPanel(
      slideDirection: SlideDirection.DOWN,
      defaultPanelState: PanelState.CLOSED
      minHeight: 192,
      maxHeight: MediaQuery.of(context).size.height,
      panel: Column(
        mainAxisAlignment: MainAxisAlignment.start,
        crossAxisAlignment: CrossAxisAlignment.start,
        children: <Widget>[
          Text('Some content'),
          Text('More content'),
        ],
      ),
    );
  }
```

![image](https://user-images.githubusercontent.com/2028673/70391807-e599e880-19b7-11ea-92cc-772b4fb40e14.png)

**Comment by wemersonrv** [comment]
After using it a litle, the content starts to appears... but missconfigured. See:

https://drive.google.com/file/d/1axJi391EARk33l6eqpRfet2B7uBu2U3o/view?usp=sharing

I need to show a initial portion of content top, and hide the rest... and when slid down, reveal the bottom of content...  I think it's not an error or bug and am doing something wrong.

Can you help me...

**Comment by akshathjain** [comment]
The panel is being rendered underneath the AppBar. You can fix this by either removing the AppBar, or adding padding to the top of your panel content that's equivalent to the height of the AppBar.
