### ISSUE TITLE
Snapping points

### ISSUE THREAD

**Issue by quantosapplications** [akshathjain/sliding_up_panel#86]
Hello, awesome plugin, thank you!
Is it possibile to define different snapping points between 0 (closed) and 1 (opened)?
Like google maps for example.
And also it would be great if I could dismiss panel dragging down like bottom sheet modal.

Thank you!

**Comment by quantosapplications** [comment]
Added a pr to provide this functionality 
https://github.com/akshathjain/sliding_up_panel/pull/89

**Comment by akshathjain** [comment]
Related to #12

**Comment by akshathjain** [comment]
Implemented and will be pushed in v1.0.1.
