### ISSUE TITLE
Can't open panel programmatically

### ISSUE THREAD

**Issue by LucasED78** [akshathjain/sliding_up_panel#95]
I try to open the panel programmatically and doesn't work. This is the code where I set the controller:

```dart 
@override
  Widget build(BuildContext context) {
    final PanelController _controller = PanelController();
    final List<Widget> _options = getOptions(_controller);

    return SlidingUpPanel(
      controller: _controller,
      minHeight: 0,
      panel: PerfilEditItem(),
      body: ListView.builder(
        itemCount: _options.length,
        itemBuilder: (_, index){
          return _options[index];
        },
      ),
    );
  }
```

And this is the place where I call the open method: 

```dart
UserDetailRow(
 title: "Dados Pessoais",
 onPressed: (){
    print(controller);
    controller.open();
  },
),
```

This is the log output I received:

```dart
════════════════════════════════════════════════════════════════════════════════════════════════════
I/flutter (31394): Instance of 'PanelController'

════════ (2) Exception caught by gesture ═══════════════════════════════════════════════════════════
The method 'call' was called on null.
Receiver: null
Tried calling: call()
════════════════════════════════════════════════════════════════════════════════════════════════════
```

**Comment by akshathjain** [comment]
@LucasED78 can you provide a sample main.dart to replicate this? It seems like you’re calling a panelController method before the SlidingUpPanel widget is rendered.

**Comment by Injazz** [comment]
i think you have to call `_controller.open()` instead of `controller.open()` since `_controller` was assigned as controller for the panel

**Comment by danielhuoo** [comment]
> i think you have to call `_controller.open()` instead of `controller.open()` since `_controller` was assigned as controller for the panel

That's not the key problem.

**Comment by akshathjain** [comment]
@LucasED78 any update on the sample `main.dart`? I won't be able to address the issue until I'm able to reproduce it in your context.

**Comment by akshathjain** [comment]
Closing due to lack of response. Feel free to reopen if you encounter this issue again.
